<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>job_moxa</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Quartz">
      <HintPath>..\references\quartz-release-net8.0\Quartz.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
