<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>$(MSBuildProjectName.Replace("_Daemon", ""))</RootNamespace>
    <AssemblyName>$(MSBuildProjectName.Replace("_Daemon", "-Service"))</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DeviceTable\**" />
    <Content Remove="DeviceTable\**" />
    <EmbeddedResource Remove="DeviceTable\**" />
    <None Remove="DeviceTable\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Sharp7.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.3.5" />
    <PackageReference Include="S7netplus" Version="0.20.0" />
    <PackageReference Include="TinyCsvParser" Version="2.7.0" />
    <PackageReference Include="Topshelf" Version="4.3.0" />
  </ItemGroup>

</Project>
